version: "3.8"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI (guest/guest)

  music-service:
    build: .
    env_file: .env
    ports: ["4000:4000"]
    depends_on: [mongo, redis, rabbitmq]

volumes:
  mongo_data:
